import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import textwrap

class PresentationFlow:
    def __init__(self, logger):
        self.logger = logger

    def run(self, topic: str, merged_summary: str):
        self.logger.log("Generating PowerPoint presentation...")
        print("\n📊 Generating presentation...")

        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        # --- Slide 1: Title ---
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
        self._set_bg(slide, "1a1a2e")
        self._add_text(slide, topic.upper(), Inches(1), Inches(2.5),
                       Inches(11), Inches(1.5), font_size=40,
                       bold=True, color="e94560")
        self._add_text(slide, "AI-Powered Deep Research Report",
                       Inches(1), Inches(4), Inches(11), Inches(1),
                       font_size=20, color="ffffff")
        self._add_text(slide, "Generated by Multi-Agent System: GPT + Gemini + Grok",
                       Inches(1), Inches(5), Inches(11), Inches(0.8),
                       font_size=14, color="aaaaaa")

        # --- Slides from summary sections ---
        sections = self._split_into_sections(merged_summary)
        colors = ["0f3460", "16213e", "1a1a2e", "0d1b2a"]

        for i, (heading, body) in enumerate(sections[:6]):  # max 6 content slides
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            self._set_bg(slide, colors[i % len(colors)])
            self._add_text(slide, heading, Inches(0.5), Inches(0.4),
                           Inches(12), Inches(1), font_size=24,
                           bold=True, color="e94560")
            self._add_text(slide, body, Inches(0.5), Inches(1.5),
                           Inches(12), Inches(5.5), font_size=14,
                           color="dddddd")

        # --- Last Slide: Sources ---
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._set_bg(slide, "1a1a2e")
        self._add_text(slide, "Research Sources", Inches(1), Inches(1),
                       Inches(11), Inches(1), font_size=28,
                       bold=True, color="e94560")
        self._add_text(slide,
                       "• GPT-4o (OpenAI)\n• Gemini 1.5 Flash (Google)\n• Grok Beta (xAI)\n\nResearch compiled and merged by automated multi-agent orchestrator.",
                       Inches(1), Inches(2.5), Inches(11), Inches(4),
                       font_size=16, color="ffffff")

        # Save
        os.makedirs("outputs/presentations", exist_ok=True)
        filename = f"outputs/presentations/{topic[:40].replace(' ', '_')}_presentation.pptx"
        prs.save(filename)
        self.logger.log(f"Presentation saved: {filename}")
        print(f"✅ Presentation saved: {filename}")

    # ── helpers ──────────────────────────────────────────────

    def _set_bg(self, slide, hex_color: str):
        from pptx.oxml.ns import qn
        from lxml import etree
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor.from_string(hex_color)

    def _add_text(self, slide, text, left, top, width, height,
                  font_size=18, bold=False, color="ffffff"):
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(font_size)
        p.font.bold = bold
        p.font.color.rgb = RGBColor.from_string(color)

    def _split_into_sections(self, text: str):
        """Split merged text into (heading, body) pairs for slides."""
        lines = text.split("\n")
        sections = []
        current_heading = "Overview"
        current_body = []

        for line in lines:
            stripped = line.strip()
            # Detect headings: lines in ALL CAPS or starting with ## or === 
            if (stripped.startswith("##") or stripped.startswith("===") or
                    (len(stripped) > 4 and stripped == stripped.upper() and stripped.isalpha() is False)):
                if current_body:
                    body_text = "\n".join(current_body[:20])  # limit lines
                    sections.append((current_heading, body_text))
                    current_body = []
                current_heading = stripped.lstrip("#= ").strip()
            elif stripped:
                current_body.append(stripped)

        # Last section
        if current_body:
            sections.append((current_heading, "\n".join(current_body[:20])))

        # Fallback: if no sections detected, chunk the text
        if not sections:
            chunks = textwrap.wrap(text, width=600)
            sections = [(f"Research Part {i+1}", chunk) for i, chunk in enumerate(chunks[:6])]

        return sections